
export const DEFAULT_ACTION = 'DEFAULT_ACTION';
export const DEFAULT_ACTION_SUCCESS = 'DEFAULT_ACTION_SUCCESS';
export const DEFAULT_ACTION_FAIL = 'DEFAULT_ACTION_FAIL';
export const LOGIN = 'LOGIN';